"""Initial: create all tables with proper schema

Revision ID: 0f6c2e1c8acf
Revises: 
Create Date: 2026-06-25 16:22:40.996992

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f6c2e1c8acf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trucks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('license_plate', sa.String(length=20), nullable=False),
    sa.Column('brand', sa.String(length=50), nullable=True),
    sa.Column('capacity_ton', sa.Float(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('fuel_rate', sa.Float(), nullable=True, comment='Liters per 100km'),
    sa.Column('current_km', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('license_plate')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=15), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('current_truck_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['current_truck_id'], ['trucks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('current_truck_id', name='uq_driver_truck')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('cargo_type', sa.String(length=100), nullable=True),
    sa.Column('default_origin', sa.String(length=200), nullable=True),
    sa.Column('default_destination', sa.String(length=200), nullable=True),
    sa.Column('contact_phone', sa.String(length=15), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fuel_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('truck_id', sa.Integer(), nullable=False),
    sa.Column('liters', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('price_per_liter', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_cost', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('km_at_refuel', sa.Integer(), nullable=True),
    sa.Column('refuel_date', sa.Date(), nullable=False),
    sa.Column('is_substitute', sa.Boolean(), nullable=True, comment='Tài xế đổ xăng cho xe không phải xe mặc định của mình (chạy giùm)'),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['truck_id'], ['trucks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fuel_prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('price_per_liter', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('effective_from', sa.DateTime(), nullable=False, comment='Thời điểm bắt đầu hiệu lực'),
    sa.Column('effective_to', sa.DateTime(), nullable=True, comment='NULL = đang hiệu lực'),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('phoi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phoi_number', sa.String(length=20), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('truck_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('departure_date', sa.Date(), nullable=False),
    sa.Column('return_date', sa.Date(), nullable=True),
    sa.Column('origin', sa.String(length=200), nullable=False),
    sa.Column('destination', sa.String(length=200), nullable=False),
    sa.Column('cargo_description', sa.String(length=300), nullable=True),
    sa.Column('km_start', sa.Integer(), nullable=True),
    sa.Column('km_end', sa.Integer(), nullable=True),
    sa.Column('km_total', sa.Integer(), nullable=True),
    sa.Column('revenue_full', sa.Numeric(precision=12, scale=2), nullable=True, comment='Tổng doanh thu full chuyến'),
    sa.Column('revenue_collected', sa.Numeric(precision=12, scale=2), nullable=True, comment='Tiền mặt tài xế đã thu'),
    sa.Column('driver_wage', sa.Numeric(precision=12, scale=2), nullable=True, comment='Phí công tài xế (manager nhập)'),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('confirmed_by_id', sa.Integer(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['confirmed_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['driver_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['truck_id'], ['trucks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phoi_number')
    )
    op.create_table('fuel_log_phois',
    sa.Column('fuel_log_id', sa.Integer(), nullable=False),
    sa.Column('phoi_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['fuel_log_id'], ['fuel_logs.id'], ),
    sa.ForeignKeyConstraint(['phoi_id'], ['phoi.id'], ),
    sa.PrimaryKeyConstraint('fuel_log_id', 'phoi_id')
    )
    op.create_table('phoi_expenses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phoi_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=30), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['phoi_id'], ['phoi.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('phoi_expenses')
    op.drop_table('fuel_log_phois')
    op.drop_table('phoi')
    op.drop_table('fuel_prices')
    op.drop_table('fuel_logs')
    op.drop_table('customers')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))

    op.drop_table('users')
    op.drop_table('trucks')
    # ### end Alembic commands ###
