"""add notification tracking columns to trucks

Revision ID: 406506709a7c
Revises: 4bf8cef8c966
Create Date: 2026-06-26 15:25:04.887442

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '406506709a7c'
down_revision = '4bf8cef8c966'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trucks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_inspection_notified_at', sa.DateTime(), nullable=True, comment='Lần cuối thông báo đăng kiểm sắp hết hạn'))
        batch_op.add_column(sa.Column('last_permit_notified_at', sa.DateTime(), nullable=True, comment='Lần cuối thông báo phù hiệu sắp hết hạn'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trucks', schema=None) as batch_op:
        batch_op.drop_column('last_permit_notified_at')
        batch_op.drop_column('last_inspection_notified_at')

    # ### end Alembic commands ###
