"""add inspection and permit fields to trucks

Revision ID: 4bf8cef8c966
Revises: 0f6c2e1c8acf
Create Date: 2026-06-26 15:22:06.591727

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4bf8cef8c966'
down_revision = '0f6c2e1c8acf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trucks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('inspection_date', sa.Date(), nullable=True, comment='Ngày đăng kiểm gần nhất'))
        batch_op.add_column(sa.Column('inspection_expiry_months', sa.Integer(), nullable=True, comment='Hạn đăng kiểm (tháng)'))
        batch_op.add_column(sa.Column('permit_date', sa.Date(), nullable=True, comment='Ngày cấp phù hiệu gần nhất'))
        batch_op.add_column(sa.Column('permit_expiry_months', sa.Integer(), nullable=True, comment='Hạn phù hiệu (tháng)'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trucks', schema=None) as batch_op:
        batch_op.drop_column('permit_expiry_months')
        batch_op.drop_column('permit_date')
        batch_op.drop_column('inspection_expiry_months')
        batch_op.drop_column('inspection_date')

    # ### end Alembic commands ###
