"""add_driver_paid_to_phoi_expenses

Revision ID: 975a0bd04827
Revises: d4e5f6a7b8c9
Create Date: 2026-10-02 10:16:29.872178

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '975a0bd04827'
down_revision = 'd4e5f6a7b8c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('phoi_expenses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('driver_paid', sa.Boolean(), nullable=False, server_default=sa.false(), comment='Tài xế tự ứng tiền sửa xe bên ngoài'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('phoi_expenses', schema=None) as batch_op:
        batch_op.drop_column('driver_paid')

    # ### end Alembic commands ###
